# Generated by Django 3.1.3 on 2020-11-26 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID única para el caso de un Alumno.', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('tema', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID única para el formulario.', primary_key=True, serialize=False)),
                ('edad', models.CharField(max_length=2)),
                ('cursos', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=60)),
                ('problema', models.CharField(max_length=200)),
                ('reporte', models.CharField(help_text='SI/NO', max_length=100)),
                ('detalle', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['problema', 'cursos'],
            },
        ),
    ]
