# Generated by Django 3.1.3 on 2020-11-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='edad',
            field=models.CharField(max_length=25),
        ),
    ]
