# Generated by Django 3.1.3 on 2020-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20201125_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='edad',
            field=models.IntegerField(verbose_name='edad'),
        ),
    ]
